### ISSUE TITLE
Fix styling on API docs page

### ISSUE THREAD

**Issue by jasonappah** [hackclub/hack-as-a-service-v0#102]
When I had my system set to dark mode, the API docs look like this, and we should probably figure out if there's a way to make the text readable in dark mode.

![image](https://user-images.githubusercontent.com/30608521/116798014-30d30080-aab1-11eb-916b-82960808e4fa.png)

**Comment by anirudhb** [comment]
Just disable theming on that page?

**Comment by jasonappah** [comment]
I think that should work, also the styling got more messed up in light mode - which I'm assuming came with the Chakra change? Spacing and text highlighting are kinda outta wack rn.

**Comment by anirudhb** [comment]
Reopening, temporary fix but there are still bugs.

**Comment by anirudhb** [comment]
Long term fix isn't necessary right now so this solution is fine as is. A proper solution is on backlog now.
