### ISSUE TITLE
HaaS CLI

### ISSUE THREAD

**Issue by cjdenio** [hackclub/hack-as-a-service-v0#120]
A CLI for managing apps, streaming logs, viewing billing, etc. (basically Heroku's CLI but better)

(i wouldn't be opposed to writing this in a non-Go language)

**Comment by anirudhb** [comment]
So is this just a command line API client?

**Comment by cjdenio** [comment]
Pretty much, yeah

**Comment by cole-wilson** [comment]
I could work on this in Python if that's an okay language, I like working on CLI's. (I can also help in another language, just won't be as helpful.)

**Comment by jasonappah** [comment]
Features we want (based on [this convo](https://hackclub.slack.com/archives/C01N3B30TFB/p1620085078073700), feel free to edit as wanted):

- [ ] Log streaming
- [ ] Package apps as .tar.gz and deploy them (unsupported by API currently)
- [ ] Viewing balances and creating invoices
- [ ] App status checking

**Comment by gleich** [comment]
I can spearhead this if you guys are cool with that. I _really_ think that we should make it in go for a few reasons:

1. The API is currently written in go so it would be easy for people working on the API to help out.
2. go compiles binaries to a static binary right out of the box so it is easy to distribute.
3. go has a number of great modules for creating cli tools that are some of the best out there.
4. Tools like [goreleaser](https://goreleaser.com/) make it _super_ easy to distribute the cli via homebrew, releases, and even a shell script.

**Comment by cole-wilson** [comment]
I agree that keeping it all in one language makes sense. I'd like to help with this, so I'll start trying to learn Go.

**Comment by quackduck** [comment]
I would not recommend python since people would then have to have python installed and python has a lot of issues with versions and installing. Since a lot of the rest of the codebase is in Go, I think that would be a good option.

**Comment by veritem** [comment]
I would like to work on this one and build the entire thing in Go

**Comment by quackduck** [comment]
Is creating a different repo for the CLI really necessary? 

CC @cjdenio @anirudhb @jasonappah

**Comment by jasonappah** [comment]
Based on slack discussion it was decided we should keep it in the same
repo. My concern was that the repo would get kinda confusing to navigate
with more folders, but we can make issue/PR labels for frontend, cli, docs,
and backend so it's easy to keep track of everything, and add a more
detailed contributing guide, so that should be fine.

**Comment by quackduck** [comment]
agreed

**Comment by cjdenio** [comment]
At this point, I feel like we should just stick with a monorepo setup.
