### ISSUE TITLE
Support for non-HTTP services

### ISSUE THREAD

**Issue by jasonappah** [hackclub/hack-as-a-service-v0#126]
See [Slack discussion](https://hackclub.slack.com/archives/C01N3B30TFB/p1620084153048300) for implementation details. TL;DR: DigitalOcean gives us 16 IPv6 addresses, so we can use one for each container. This does have the caveat of only allowing 15 non-HTTP services (since we need one for the management UI) but it's better than nothing, and I don't think we'll have many of them anyway. This wasn't included in the discussion but maybe we wanna charge a little extra since these apps are basically getting their own dedicated IPs.

**Comment by quackduck** [comment]
So this is possible, right? Ani in Slack tells me this won't happen in the initial launch.

**Comment by jasonappah** [comment]
That's right. If i had to guess it'd probably come within the first couple
weeks to 1 month at the most, but don't quote me on that :)

**Comment by quackduck** [comment]
What about with that new information about floating IPs, does that mean we can get this in the initial launch? I want to help with this problem.

**Comment by jasonappah** [comment]
Still going to be probably going to be after initial launch, but definitely easier.
