### ISSUE TITLE
dokkud reconnection doesn't work

### ISSUE THREAD

**Issue by cjdenio** [hackclub/hack-as-a-service-v0#142]
I've confirmed that if you restart dokkud (`sudo service dokkud restart`), then attempt to view app logs (or take another dokku-requiring action), the request times out.

~This may be an issue with dokkud, as restarting the API doesn't seem to entirely fix the issue~ <- this was actually caused by #139

**Comment by anirudhb** [comment]
Sounds like this is an issue with backoff. Definitely gonna look into removing backoff.
