### ISSUE TITLE
Wait for deploy locks instead of dying

### ISSUE THREAD

**Issue by anirudhb** [hackclub/hack-as-a-service-v0#165]
Currently, CI will just die if a deploy lock is already held. Instead, it should wait and then deploy afterwards so that we don't get failing builds.

**Comment by cjdenio** [comment]
I'm not sure if there's a way around this; the deploy lock is run by Dokku

**Comment by anirudhb** [comment]
Somehow figure out a way to wait for it to be unlocked?

**Comment by anirudhb** [comment]
Resolved with #201
