### ISSUE TITLE
Apps without SSL don't work

### ISSUE THREAD

**Issue by cjdenio** [hackclub/hack-as-a-service-v0#186]
For some reason, apps without SSL (at least on the *.haas.hackclub.com domain), do the following:

- Redirect to their HTTPS counterparts
- 404 because there's no SSL :pain:

**Comment by quackduck** [comment]
So we'll make certs automatically for the app?

**Comment by quackduck** [comment]
I'm guessing that's how GitHub does that with Pages

**Comment by cjdenio** [comment]
Making certs automatically would be great, but it doesn't fix the fact that apps _should_ work without SSL.

**Comment by jasonappah** [comment]
And the plot thickens: Some browsers don't redirect to HTTPS, but others do... For me, Safari 14.0 doesn't, but Chrome 90 does... Not entirely sure why.

**Comment by Muirrum** [comment]
for *.haas.hackclub.com domains would it be easier to obtain a wildcard cert for that?

**Comment by anirudhb** [comment]
That's a security risk since it lets one app impersonate other apps. Also fwiw we have a wildcard cert for the "app not found" page

**Comment by anirudhb** [comment]
Resolved with #201
