### ISSUE TITLE
When deploying logs have strange unicode errors

### ISSUE THREAD

**Issue by l3gacyb3ta** [hackclub/hack-as-a-service-v0#188]
![image](https://user-images.githubusercontent.com/58434499/117491627-71fa6300-af3e-11eb-87c1-63b4e2c3bbf0.png)
As you can see, it's this strange [1G character.

**Comment by cjdenio** [comment]
This is due to ANSI color codes; basically, a terminal would know how to interpret those and display color accordingly. Someday (hopefully soon), we'll be able to render log colors on the frontend 🤞
