### ISSUE TITLE
Create example Dockerfiles/Procfiles

### ISSUE THREAD

**Issue by jasonappah** [hackclub/hack-as-a-service-v0#19]
Once we're close to launching this, it'd be nice to have examples of what is needed to deploy applications. Imo we should include examples for:

- [ ] Express.js
- [ ] Flask
- [ ] Next.js
- [ ] Plain static sites
- [ ] Whatever other frameworks are hip with the kids nowadays lol

**Comment by veritem** [comment]
@cjdenio or @jasonappah  are we going to add examples folder like how vercel does it or write it up inside documentation would like to help with this.

**Comment by jasonappah** [comment]
I was leaning towards more of how Vercel does it in their examples folder.
Sam just made a docs site as well so we can have more detailed guides on
there.

**Comment by quackduck** [comment]
Oh also one with a non-HTTP service (to demonstrate that's possible)

**Comment by jasonappah** [comment]
Yep, setting up a non-HTTP service is going to be a bit more involved, so
that'd probably be something to have a full guide for on the docs site.

**Comment by veritem** [comment]
@jasonappah  when we get done with the deployment stuffs i would like to work on this one
