### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by anirudhb** [hackclub/hack-as-a-service-v0#5]
Dokku doesn't have a web UI so we need to write our own and serve it from the Go server.

Probably would end up using Next.js or something, or maybe some other framework.

**Comment by cjdenio** [comment]
This should be broken into sub-issues.

**Comment by sampoder** [comment]
yes that is what confused me

**Comment by cjdenio** [comment]
Closing as we can create issues for specific frontend pages/features

**Comment by sampoder** [comment]
ok
