### ISSUE TITLE
GitHub integration

### ISSUE THREAD

**Issue by cjdenio** [hackclub/hack-as-a-service-v0#50]
Create a GitHub app for deploying apps from GitHub repositories

**Comment by gleich** [comment]
@cjdenio did you want to work on this? I would love to make it :)

**Comment by jasonappah** [comment]
Had some important discussions on Slack regarding implementation of this on the frontend and API:

https://hackclub.slack.com/archives/C01N3B30TFB/p1620182268407300
https://hackclub.slack.com/archives/C01N3B30TFB/p1620183053429800
