### ISSUE TITLE
Set resource limits for builders

### ISSUE THREAD

**Issue by cjdenio** [hackclub/hack-as-a-service-v0#6]
A common issue with running Docker build processes on is that it consumes a massive amount of CPU for a short period, and can even crash the server entirely (especially Node.js and Rust apps in my experience). We can fix this by setting resource limits on the builder containers so they don't take down the whole server. This also allows us to provide a good experience to customers without placing extreme load on the server.

**Comment by jasonappah** [comment]
Sounds like this will be useful for restricting container resources: https://dokku.com/docs/advanced-usage/resource-management/

Re builds: I think modifying [dokku's build args](https://github.com/dokku/dokku/blob/23a54f58b05f7e7c51e42cfce2593de7cef8205f/dokku#L67) with options described [here](https://docs.docker.com/engine/reference/commandline/build/#options) should do the trick.

**Comment by anirudhb** [comment]
See #201 as our strategy has to be changed
