### ISSUE TITLE
Frontend *.html files aren't served correctly

### ISSUE THREAD

**Issue by cjdenio** [hackclub/hack-as-a-service-v0#61]
The dashboard should be accessible at /dashboard, not /dashboard.html

**Comment by anirudhb** [comment]
Reopening since #62 was just a temporary fix. It would be much more preferable to auto-generate a route map based on the `*.html` files present in the frontend's build output.

**Comment by cjdenio** [comment]
@anirudhb i can start working on this if it's fine by you

**Comment by cjdenio** [comment]
I've been researching the "right" way to do this, and I found that you can run the frontend and backend in different containers while running an Nginx proxy in a third; that might be the most containerization-y way of running both apps on a single host 🤷‍♂️
