### ISSUE TITLE
New app not found and 500 pages

### ISSUE THREAD

**Issue by cjdenio** [hackclub/hack-as-a-service-v0#75]
Now that we have a basic design, the app not found page should be tweaked.

**Comment by veritem** [comment]
@cjdenio  what's remaining on this ???

**Comment by cjdenio** [comment]
The page at https://github.com/hackclub/hack-as-a-service/blob/master/dokku_deploy/var/lib/dokku/data/nginx-vhosts/dokku-errors/haas/404-error.html needs to be updated to match the current design system (right now it looks like [this](https://404.haas.hackclub.com))

**Comment by veritem** [comment]
Do we have any design for 404 page?

**Comment by bellesea** [comment]
@cjdenio do you need help with this?

**Comment by bellesea** [comment]
> Do we have any design for 404 page?

@makuzaverite 
I don't think so? but we can just base it off the existing design for other pages: https://www.figma.com/file/vGT8ifd6Em2YGy428kGQEg/Hack-as-a-Service?node-id=0%3A1 

or even just this page: https://haas.hackclub.com
