### ISSUE TITLE
Build app settings page

### ISSUE THREAD

**Issue by jasonappah** [hackclub/hack-as-a-service-v0#82]
Build the app settings page at `/:app/settings`.

As of the making of this issue, the page should look like this, but please double-check the [Figma](https://www.figma.com/file/vGT8ifd6Em2YGy428kGQEg/Hack-as-a-Service?node-id=0%3A1) before building this page: 

![A screenshot of a mockup for this page](https://user-images.githubusercontent.com/30608521/116757387-96e95600-a9d3-11eb-9dd2-e0e53ac1d638.png)
![A screenshot of a mockup for this page](https://user-images.githubusercontent.com/30608521/116757415-a36dae80-a9d3-11eb-8ff2-fbb2e32f3169.png)

Any design feedback is welcome. AFAIK the API endpoint for this hasn't been made yet.

**Comment by exu3** [comment]
Sorry I'm a bit backed up rn, so I'm unclaiming this issue in case someone else can get to it before me. 

But I will claim an issue and work on something once I have some time.

**Comment by jasonappah** [comment]
No problem!
