### ISSUE TITLE
Create remaining designs

### ISSUE THREAD

**Issue by jasonappah** [hackclub/hack-as-a-service-v0#85]
Designs are close to being done. As of now, all the pages we need mocked up are:

- [x] App integrations page (GitHub deployments and Slack notifications)
- [x] Account settings (needs to export/update/delete user info, see #87)
- [x] Team settings (manage team name and eventually be able to delete a team if it doesn't have apps associated with it)
- [x] Team member management (so we'll remove that module from the main team page)
- [x] Also figure out the deployment section of the [apps](https://www.figma.com/file/vGT8ifd6Em2YGy428kGQEg/Hack-as-a-Service?node-id=27%3A113) page
- [x] GitHub setup for teams (see #50)

**Comment by bellesea** [comment]
@jasonappah do you need help with this? i think i already see a github deploy thing on figma?

**Comment by jasonappah** [comment]
We're all good here, thanks for asking! I'll close this issue now/
